# These are required.
# If only name is specified, it will look in your system PATH variable, which includes the current directory on Windows.
# Setup instructions: https://github.com/pcroland/deew#setup-system-path-variable
# If full path is specified, that will be used.
ffmpeg_path = 'apps\FFmpeg\bin\ffmpeg.exe'
ffprobe_path = 'apps\FFmpeg\bin\ffprobe.exe'
dee_path = 'apps\DEE\dee.exe'

# If this is empty, the default OS temporary directory will be used (or `temp` next to the script if you use the exe).
# You can also specify an absolute path or a path relative to the current directory.
temp_path = ''

# Set between 1 and 10, use the -pl/--print-logos option to see the available logos, set to 0 to disable logo.
logo = 1

# Specifies how many encodes can run at the same time.
# It can be a number or a % compared to your number of threads (so '50%' means 4 on an 8 thread cpu).
# One DEE can use 2 threads so setting '50%' can utilize all threads.
# You can override this setting with -in/--instances.
# The number will be clamped between 1 and cpu_count().
# With the Windows version of DEE the max will be cpu_count() - 2 or 6 due to a limitation.
# examples: 1, 4, '50%'
max_instances = '50%'

[default_bitrates]
    dd_1_0 = 112
    dd_2_0 = 224
    dd_5_1 = 640
    ddp_1_0 = 112
    ddp_2_0 = 224
    ddp_5_1 = 640
    ddp_7_1 = 768
    ac4_2_0 = 320

# You can toggle what sections you would like to see in the encoding summary
[summary_sections]
    deew_info = true
    binaries = true
    input_info = true
    output_info = true
    other = true
